<?php

use Tests\TestCase;
use Illuminate\Routing\Controller;


class LucTestController extends TestCase
{

    public Controller $middleware;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @dataProvider dataTestLogin
     */
    public function login(array $data)
    {
        $response = $this->postJson('api/login', $data);
        $response->assertStatus(200);
        $this->assertDatabaseHas('users', [
            ''
        ]);
    }

    public static function dataTestLogin(): array
    {
        return [
            [
                'email' => 'abbott.darrel@baumbach.com',
                'password' => 'GF`l<m',
            ],
        ];
    }


    /**
     * @test
     * @dataProvider dataTestRegister
     */
    public function register(array $dataTestRegister)
    {
        $response = $this->postJson('api/register', $dataTestRegister);
        $response->assertStatus(200);
        $this->assertDatabaseHas('users', []);
    }

    public static function dataTestRegister()
    {
        return [
            [
                'id' => 2,
                'name' => 'Glennie Renner',
                'email' => 'abbott.darrel@baumbach.com',
                'email_verified_at' => '1984-03-28 18:50:08',
                'password' => 'GF`l<m',
                'remember_token' => '4eudo0qXf52eGccjdD2iQvuPZ2gMklyjE56LOWd9',
                'created_at' => '2022-05-23 19:29:34',
                'updated_at' => '1971-05-23 14:30:42',
            ],
        ];
    }


    /**
     * @test
     * @dataProvider dataTestLogout
     */
    public function logout(array $dataTestLogout)
    {

    }

    public static function dataTestLogout()
    {
        return [
            [
                'id' => 2,
                'name' => 'Glennie Renner',
                'email' => 'abbott.darrel@baumbach.com',
                'email_verified_at' => '1984-03-28 18:50:08',
                'password' => 'GF`l<m',
                'remember_token' => '4eudo0qXf52eGccjdD2iQvuPZ2gMklyjE56LOWd9',
                'created_at' => '2022-05-23 19:29:34',
                'updated_at' => '1971-05-23 14:30:42',
            ],
        ];
    }

}
